### ISSUE TITLE
PDL::Ngrams::Utils vs ::PDL::Ngrams::ngutils

### ISSUE THREAD

**Issue by mohawk2** [moocow-the-bovine/PDL-Ngrams#1]
Some of the POD (and some of the distro stuff like `MANIFEST.SKIP`) refers to PDL::Ngrams::ngutils, but the actual module is called PDL::Ngrams::Utils.

Also, MetaCPAN can't see this repo in its metadata :-)

**Comment by moocow-the-bovine** [comment]
should be fixed in 8aa9071, uploaded to CPAN as v0.11

[EDIT: I neglected to update MANIFEST.SKIP before bumping & uploading - it's fixed now in git master, but the changes probably won't make it onto CPAN until the next release]

**Comment by mohawk2** [comment]
Looks great! Close when you prefer.

I note you have the repo `url` as `git://github.com/moocow-the-bovine/PDL-Ngrams.git`, but with https://github.blog/2021-09-01-improving-git-protocol-security-github/ this is no longer valid.

**Comment by moocow-the-bovine** [comment]
thanks for the tip!

The `git://`-URL has been replaced with https in the CPAN metadata, now uploaded as v0.12.
